### ISSUE TITLE
Why should the duration of the delayed job completion timer be left at 15 mins?

### ISSUE THREAD

**Issue by woobenjamin** [leofabri/hassio_appliance-status-monitor#37]
Hi,
Thank you for this blueprint! After trying to do this myself for weeks, it was great to take advantage of what you have created. As I looked through the configuration, I came across the following:

```
timer:
  dryer_delayed_job_completion_timer:
    name: Dryer - Delayed Job Completion Timer
    duration: "00:15:00" # <- Note that the time here. Leave as it is (15 min)
    restore: true
    icon: mdi:tumble-dryer
```

I'm wondering why the duration should be left as it is at 15 mins. The reason for my question is that I like having my dishwasher wait for 2 hours before declaring the job done so that it can dry properly.

Can you advise if changing this to a longer or shorter time is OK?

Thank you!

Ben
